pipeline {
    agent any
    tools {nodejs "node1415"}

    environment {
        APP_NAME = "siat-frontend-dev"
        NAMESPACE = "infp"
        DOCKER_IMAGE = "siat-frontend-dev"
        TAG = "${BUILD_NUMBER}"
        DOCKER_IMAGENAME = "${DOCKER_IMAGE}:${TAG}"
        SVCTYPE = "NodePort"
        NODEPORT = "30507"
        MODE = "dev"
    }

    stages {
        stage('project build'){
            steps{
                dir('frontend'){
                    sh 'yarn install'
                    sh 'yarn build'
                }
            }
        }
        stage('docker build&push'){
            steps{
                dir('frontend'){
                    sh 'rm -rf ./Dockerfile Jenkinsfile charts'
                    sh 'cp -rf cicd/dev/* ./'
                    withCredentials([string(credentialsId: 'dockerID', variable: 'dockerID')]) {
                        script{
                            sh 'docker build -t ${dockerID}/${DOCKER_IMAGENAME} .'
                            withCredentials([usernamePassword(credentialsId: 'docker', passwordVariable: 'dockerpassword', usernameVariable: 'dockeruser')]) {
                                sh 'docker login -u ${dockeruser} -p ${dockerpassword}'
                                sh 'docker push ${dockerID}/${DOCKER_IMAGENAME}'
                            }
                        }
                    }
                }
            }
        }
        stage('deploy'){
            steps{
                dir('frontend'){
                    withCredentials([string(credentialsId: 'dockerID', variable: 'dockerID')]) {
                        sh 'sed -i "s/__IMAGENAME__/${dockerID}\\/${DOCKER_IMAGE}/g" charts/values.yaml'
                        sh 'sed -i "s/__TAGNAME__/${TAG}/g" charts/values.yaml'
                        sh 'sed -i "s/__SVCTYPE__/${SVCTYPE}/g" charts/values.yaml'
                        sh 'sed -i "s/__NODEPORT__/${NODEPORT}/g" charts/values.yaml'
                        sh 'sed -i "s/__MODE__/${MODE}/g" charts/values.yaml'
                        sh "helm upgrade --install --namespace ${NAMESPACE} ${APP_NAME} ./charts"
                    }
                }
            }
        }
    }
}
