replicaCount: 1

image:
  repository: __IMAGENAME__
  pullPolicy: IfNotPresent
  tag: __TAGNAME__

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 9400
  targetPort: 9400

ingress:
  enabled: true
  ingressClassName: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letencrypt-prod"
    certmanager.k8s.io/acme-challenge-type: dns01
  hosts:
    - host: __HOST1__
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: __TLS__SECRETNAME__
      hosts:
        - __HOST1__

resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 300m
    memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

application:
  secret:
    jasypt: __JASYPT__
  mode: __MODE__
