pipeline {
    agent any
    tools {gradle "gradle"}

    environment {
        DOCKER_IMAGE = "siat-dev-backend"
        TAG = "${BUILD_NUMBER}"
        DOCKER_IMAGENAME = "${DOCKER_IMAGE}:${TAG}"
        SVCTYPE = "NodePort"
        NODEPORT = "30506"
        JASYPT_KEY = credentials('SIAT_DEV_JASYPT')
        MODE = "dev"
    }

    stages {
        stage('git checkout') {
            steps {
                checkout changelog: false, poll: false, scm: [$class: 'GitSCM', branches: [[name: '*/develop']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/INFP-Study/CIAT.git']]]
            }
        }
        stage('project build'){
            steps{
                dir('backend'){
                    withGradle {
                        sh 'gradle clean build --exclude-task test'
                    }
                }
            }
        }
        stage('docker build&push'){
            steps{
                dir('backend'){
                    sh 'cp -rf cicd/dev ./'
                    withCredentials([string(credentialsId: 'dockerID', variable: 'dockerID')]) {
                        script{
                            sh 'docker build -t ${dockerID}/${DOCKER_IMAGENAME} .'
                            withCredentials([usernamePassword(credentialsId: 'docker', passwordVariable: 'dockerpassword', usernameVariable: 'dockeruser')]) {
                                sh 'docker login -u ${dockeruser} -p ${dockerpassword}'
                                sh 'docker push ${dockerID}/${DOCKER_IMAGENAME}'
                            }
                        }
                    }
                }
            }
        }
        stage('deploy'){
            steps{
                dir('backend'){
                    withCredentials([string(credentialsId: 'dockerID', variable: 'dockerID')]) {
                        sh 'sed -i "s/__IMAGENAME__/${dockerID}\\/${DOCKER_IMAGE}/g" charts/values.yaml'
                        sh 'sed -i "s/__TAGNAME__/${dockerID}\\/${TAG}/g" charts/values.yaml'
                        sh 'sed -i "s/__JASYPT__/${JASYPT_KEY}/g" charts/values.yaml'
                        sh 'sed -i "s/__SVCTYPE__/${SVCTYPE}/g" charts/values.yaml'
                        sh 'sed -i "s/__NODEPORT__/${NODEPORT}/g" charts/values.yaml'
                        sh 'sed -i "s/__MODE__/${MODE}/g" charts/values.yaml'
                        helm upgrade  --install ./charts
                    }
                }
            }
        }
    }
}
