spring:
  security:
    oauth2:
      client:
        # registration
        registration:
          # google oauth2 setting
          google:
            client-id: ENC(9x1WuXePNRbn3jybwjlZqlX/6s05qbc2HCtpGTgyi2v8LRiS01SY47m9yxI0z+vJC2WjIzfORBwPXkPFdCA7GbnfxpegFViJAGn//8PzTsFi0OT1up7rNwkPCH6v7tyft1vRKMui//2zl3bozLD7KA==)
            client-secret: ENC(hLZ8XuiW5fkOrN8mFCkiSN9vv18CsUXgX4u5xFO6donjjUh3SkknEsSUPv9SUCOm8F+e3sWLa3NCRE1YJ6amigszQrWJVzVjhLw+ruz4jMU=)
            scope:
              - profile
              - email

          # github oauth2 setting
          github:
            client-id: ENC(VznZ2i71zRHnK0Jp18c9TjBAIojSq6PmD2SbjnsAGPR/J0HGZYtiZYYO1TmwdvgJf+jlX5Uv89u8HV23gIN6DQ==)
            client-secret: ENC(jaaGjh4SHn8bNHNeqR1czfVizcolh3yEgpV92ynANcXugWHaAqJ9f2ABZIN9s/1NBhl2mX7ujZswTJyTh+90vuT2yMMeC9hiEf6SQft5kVQ=)
